---
title: "fig7H"
author: "l1ming"
date: '2025-10-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(ggpmisc) 
library(ggrepel)
library(patchwork)
library(stringr)

```


```{r}
load('fig7H.Rdata')
p_cut=0.05
logfc_cut=0.5
g = "C9ORF50"

vol = ires %>% 
    ggplot(aes(x=log2FoldChange, y=-log10(padj)))+
    geom_point(aes(color = Group, size=3))+
    geom_vline(xintercept = c(-logfc_cut, logfc_cut), linetype='dashed')+
    geom_hline(yintercept = -log10(p_cut), linetype='dashed')+
    labs(x=expression(log[2]~"(Fold Change)"),
         y=expression(-log[10]~"(Adjusted P value)"),
         color = "Regulated",
         title = paste0("Chemokine expression"),
         subtitle = paste0("Grouped by ", g, " expression")) +
    ggrepel::geom_label_repel(data=ires2, force_pull = 2,  
                              mapping=aes(x=log2FoldChange,
                                          y=-log10(padj), label = Symbol),
                              max.overlaps = 500)+
    scale_color_manual(
        limits = c("Up", "Down"),
        values = ggsci::pal_aaas(alpha = 0.5)(9)[c(6, 5)]
    ) +
    scale_x_continuous(breaks = seq(-1.5, 1, 0.5)) +
    scale_y_continuous(breaks = seq(0, 3, 1)
                       ) +
           scale_color_manual(
            limits = c("Up", "-", "Down"),
            labels = c("Pos", "NS", "Neg"),
            values = ggsci::pal_aaas(alpha = 0.6)(9)[c(6, 9, 5)]
        ) +
    theme_bw() +
    theme(panel.grid = element_blank(),
          panel.border = element_rect(size=1.5),
          axis.ticks = element_line(size=1),
          text = element_text(face = 'bold'),
          axis.text = element_text(color = 'black', size=13),
          plot.title = element_text(hjust=0.5, size=17),
          plot.subtitle = element_text(hjust = 0.5, size=13),
          axis.title = element_text(size=15),
          legend.position = "none"
          )

ggsave(vol, filename = "fig7H.tiff", 
       height = 13, width = 15, units = "cm")
vol
```
